version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build: 
      context: app/
      dockerfile: Dockerfile
      args:
        DEBIAN_VARIANT: "bullseye"
        GOLANG_VERSION: "1.18"
    
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    network_mode: service:postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - postgres/.env
